# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

before_script:
  - apt-get update -qq
  - apt-get install -qy libelf1
  - npm install -g --quiet yarn
  - yarn

test:
  script:
    - yarn test

build:
  script:
    - yarn run build

pages:
  stage: deploy
  script:
    - yarn run test:unit
    - yarn run build
    - mkdir .public && mkdir .public/coverage
    - cp -r dist .public
    - mv coverage/lcov-report .public/coverage
    - mv .public public
  artifacts:
    paths:
      - public